# Generated by Django 2.2.7 on 2020-02-14 01:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('career_type', models.CharField(max_length=255)),
                ('cv_format', models.CharField(max_length=25)),
                ('cv_upload', models.FileField(upload_to='CV/%Y/%m/%d/')),
                ('agree_to_terms', models.BooleanField()),
                ('revised_cv', models.FileField(blank=True, upload_to='RevisedCV/%Y/%m/%d/')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 5, 43, 113477, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='UploadCVMailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('before_msg', models.CharField(max_length=255)),
                ('after_msg', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 5, 43, 115476, tzinfo=utc))),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.MyEmailConfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 5, 43, 114477, tzinfo=utc))),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='upload_cv.UploadCV')),
            ],
        ),
    ]
