# Generated by Django 2.2.7 on 2020-02-10 19:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('career_type', models.CharField(max_length=255)),
                ('cv_format', models.CharField(max_length=25)),
                ('cv_upload', models.FileField(upload_to='CV/%Y/%m/%d/')),
                ('agree_to_terms', models.BooleanField()),
                ('revised_cv', models.FileField(blank=True, upload_to='RevisedCV/%Y/%m/%d/')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 10, 19, 39, 46, 496846, tzinfo=utc))),
            ],
        ),
    ]
