# Generated by Django 2.2.7 on 2020-02-14 01:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upload_cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 25, 8, 336218, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uploadcv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 25, 8, 335218, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uploadcvmailmessage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 25, 8, 336218, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uploadcvmailmessage',
            name='host_user',
            field=models.EmailField(max_length=255),
        ),
    ]
