# Generated by Django 2.2.7 on 2019-12-23 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadcv',
            name='revised_cv',
            field=models.FileField(blank=True, upload_to='RevisedCV/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='uploadcv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 22, 10, 19, 722337)),
        ),
    ]
