# Generated by Django 2.2.7 on 2020-02-14 01:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upload_cv', '0002_auto_20200214_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 38, 10, 602224, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uploadcv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 38, 10, 602224, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uploadcvmailmessage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 38, 10, 603224, tzinfo=utc)),
        ),
    ]
