# Generated by Django 2.2.7 on 2019-12-24 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_cv', '0003_auto_20191224_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 24, 14, 46, 30, 32041)),
        ),
        migrations.AlterField(
            model_name='uploadcv',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
