# Generated by Django 2.2.7 on 2019-12-25 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_cv', '0008_auto_20191225_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 25, 14, 14, 14, 909205)),
        ),
    ]
