# Generated by Django 2.2.7 on 2020-01-19 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_cv', '0010_auto_20200119_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcv',
            name='agree_to_terms',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='uploadcv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 14, 18, 11, 55033)),
        ),
    ]
