# Generated by Django 2.2.7 on 2020-01-19 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_cv', '0011_auto_20200119_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcv',
            name='agree_to_terms',
            field=models.CharField(default='false', max_length=10),
        ),
        migrations.AlterField(
            model_name='uploadcv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 14, 19, 20, 216119)),
        ),
    ]
