# Generated by Django 2.2.7 on 2020-01-19 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_cv', '0012_auto_20200119_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 14, 26, 57, 269097)),
        ),
    ]
