# Generated by Django 2.2.7 on 2020-01-19 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_cv', '0014_auto_20200119_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 17, 44, 45, 692728)),
        ),
    ]
