# Generated by Django 2.2.7 on 2020-01-20 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upload_cv', '0019_auto_20200120_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 9, 57, 50, 421361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leftad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 9, 57, 50, 422359, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rightad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 9, 57, 50, 422359, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 9, 57, 50, 420360, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uploadcv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 9, 57, 50, 419362, tzinfo=utc)),
        ),
    ]
