# Generated by Django 2.2.7 on 2020-02-14 01:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyEmailConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=30)),
                ('port', models.IntegerField()),
                ('host_user', models.EmailField(max_length=255, unique=True)),
                ('host_password', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 5, 43, 112478, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='ShortListCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='short_list/%Y/%m/%d/')),
                ('font_awesome_class', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 5, 43, 111479, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('testimony', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 5, 43, 110479, tzinfo=utc))),
            ],
        ),
    ]
