# Generated by Django 2.2.7 on 2020-02-10 19:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('testimony', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 10, 19, 39, 46, 494850, tzinfo=utc))),
            ],
        ),
    ]
