# Generated by Django 2.2.7 on 2020-02-14 01:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upload_cv', '0002_auto_20200214_0125'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyEmailConfiguration',
        ),
        migrations.AlterField(
            model_name='shortlistcompanies',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 25, 8, 333220, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 25, 8, 333220, tzinfo=utc)),
        ),
    ]
