# Generated by Django 2.2.7 on 2020-02-14 01:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200214_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlistcompanies',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 38, 10, 600226, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 38, 10, 599227, tzinfo=utc)),
        ),
    ]
