# Generated by Django 2.2.7 on 2020-02-14 01:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200214_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlistcompanies',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 43, 49, 903424, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 43, 49, 902424, tzinfo=utc)),
        ),
    ]
