# Generated by Django 2.2.7 on 2020-02-10 21:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200210_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortListCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='short_list/%Y/%m/%d/')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 10, 21, 3, 19, 378246, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 21, 3, 19, 377247, tzinfo=utc)),
        ),
    ]
