# Generated by Django 2.2.7 on 2020-02-10 23:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200210_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistcompanies',
            name='font_awesome_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shortlistcompanies',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 23, 39, 24, 884584, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shortlistcompanies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='short_list/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 23, 39, 24, 883584, tzinfo=utc)),
        ),
    ]
