# Generated by Django 2.2.7 on 2020-01-20 18:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200120_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerads',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 18, 1, 33, 952535, tzinfo=utc)),
        ),
    ]
