# Generated by Django 2.2.7 on 2020-02-18 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200218_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortlistcompanies',
            old_name='image',
            new_name='logo_image',
        ),
        migrations.AlterField(
            model_name='shortlistcompanies',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 12, 32, 0, 902764, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 12, 32, 0, 901765, tzinfo=utc)),
        ),
    ]
