# Generated by Django 2.2.7 on 2020-01-30 15:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200126_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerads',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 15, 55, 6, 553038, tzinfo=utc)),
        ),
    ]
