# Generated by Django 2.2.7 on 2020-02-14 01:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAdRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rate', models.FileField(upload_to='BannerAds/%Y/%m/%d/')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 5, 43, 117475, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='BottomAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='BannerAds/Portfolio/BottomAd/%Y/%m/%d/')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 5, 43, 119474, tzinfo=utc))),
                ('expiry', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LeftAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='BannerAds/Portfolio/LeftAd/%Y/%m/%d/')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 5, 43, 120473, tzinfo=utc))),
                ('expiry', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='BannerAds/Portfolio/PortfolioAd/%Y/%m/%d/')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 5, 43, 120473, tzinfo=utc))),
                ('expiry', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RightAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='BannerAds/Portfolio/RightAd/%Y/%m/%d/')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 5, 43, 119474, tzinfo=utc))),
                ('expiry', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TopAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='BannerAds/Portfolio/TopAd/%Y/%m/%d/')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 5, 43, 118475, tzinfo=utc))),
                ('expiry', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
