# Generated by Django 2.2.7 on 2020-02-14 01:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneradrate',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 25, 8, 339216, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 25, 8, 341216, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leftad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 25, 8, 344213, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolioad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 25, 8, 345212, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rightad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 25, 8, 343215, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 25, 8, 340217, tzinfo=utc)),
        ),
    ]
