# Generated by Django 2.2.7 on 2020-02-10 20:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerads',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 20, 25, 5, 364822, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 20, 25, 5, 366820, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leftad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 20, 25, 5, 367819, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolioad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 20, 25, 5, 367819, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rightad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 20, 25, 5, 366820, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 20, 25, 5, 365821, tzinfo=utc)),
        ),
    ]
