# Generated by Django 2.2.7 on 2020-02-10 20:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_auto_20200210_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAdsRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rate', models.FileField(upload_to='BannerAds/%Y/%m/%d/')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 10, 20, 43, 12, 646717, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='BannerAds',
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 20, 43, 12, 647719, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leftad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 20, 43, 12, 648718, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolioad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 20, 43, 12, 649717, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rightad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 20, 43, 12, 648718, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 20, 43, 12, 646717, tzinfo=utc)),
        ),
    ]
