# Generated by Django 2.2.7 on 2020-02-14 01:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_auto_20200214_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneradrate',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 43, 49, 909421, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 43, 49, 910420, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leftad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 43, 49, 912419, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolioad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 43, 49, 914418, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rightad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 43, 49, 911419, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 43, 49, 910420, tzinfo=utc)),
        ),
    ]
