# Generated by Django 2.2.7 on 2020-02-14 01:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('slug_field', models.CharField(max_length=255)),
                ('summary', models.TextField(max_length=255)),
                ('meta_content', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='Blog/%Y/%m/%d/')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 5, 43, 124470, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='TopAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='BannerAds/Blog/TopAd/%Y/%m/%d/')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 14, 1, 5, 43, 125470, tzinfo=utc))),
                ('expiry', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
