# Generated by Django 2.2.7 on 2020-01-19 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(max_length=255)),
                ('meta_content', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='Blog/%Y/%m/%d/')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 1, 19, 17, 44, 45, 696724))),
            ],
        ),
    ]
