# Generated by Django 2.2.7 on 2020-01-20 10:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200120_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='BannerAds/Blog/TopAd/%Y/%m/%d/')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 1, 20, 10, 54, 49, 757922, tzinfo=utc))),
                ('expiry', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 10, 54, 49, 756922, tzinfo=utc)),
        ),
    ]
