# Generated by Django 2.2.7 on 2019-12-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_link',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
