# Generated by Django 2.2.7 on 2019-12-24 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_portfolio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 24, 16, 55, 54, 68573)),
        ),
    ]
