# Generated by Django 2.2.7 on 2020-02-18 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200218_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 12, 32, 0, 922752, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 12, 32, 0, 919754, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfoliomailmessage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 12, 32, 0, 923750, tzinfo=utc)),
        ),
    ]
