# Generated by Django 2.2.7 on 2020-02-10 21:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200210_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 21, 3, 19, 386241, tzinfo=utc)),
        ),
    ]
