# Generated by Django 2.2.7 on 2019-12-25 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20191225_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 25, 14, 14, 14, 980954)),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
