# Generated by Django 2.2.7 on 2020-01-20 18:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_auto_20200120_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='banner_ad',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.TopAd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 18, 1, 34, 26489, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leftad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 18, 1, 34, 28488, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 18, 1, 34, 28488, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rightad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 18, 1, 34, 27488, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 18, 1, 34, 26489, tzinfo=utc)),
        ),
    ]
