# Generated by Django 2.2.7 on 2020-01-30 15:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_auto_20200130_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 15, 57, 18, 629562, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leftad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 15, 57, 18, 631058, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 15, 57, 18, 633554, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolioad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 15, 57, 18, 631558, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolioad',
            name='image',
            field=models.ImageField(blank=True, upload_to='BannerAds/Portfolio/PortfolioAd/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='portfolioad',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rightad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 15, 57, 18, 630560, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topad',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 15, 57, 18, 629063, tzinfo=utc)),
        ),
    ]
